local error = error
local sgmatch = string.gmatch

local scaffold_conf = require 'lor.scaffold.config'
local ngx_handle = require 'lor.scaffold.nginx.handle'
local ngx_config = require 'lor.scaffold.nginx.config'
local ngx_conf_template = require 'lor.scaffold.nginx.conf_template'
local utils = require 'lor.lib.utils'


local Lor = {}

function Lor.nginx_conf_content()
    -- read nginx.conf file
    local nginx_conf_template =  ngx_conf_template.get_ngx_conf_template()

    -- append notice
    nginx_conf_template = [[
    #generated by `lor framework`
    ]] .. nginx_conf_template

    local match = {}
    local tmp = 1
    for v in sgmatch(nginx_conf_template , '{{(.-)}}') do
        match[tmp] = v
        tmp = tmp + 1
    end

    for _, directive in ipairs(match) do
        if ngx_config[directive] ~= nil then
            nginx_conf_template = string.gsub(nginx_conf_template, '{{' .. directive .. '}}', ngx_config[directive])
        else
            nginx_conf_template = string.gsub(nginx_conf_template, '{{' .. directive .. '}}', '#' .. directive)
        end
    end

    return nginx_conf_template
end

function new_handler()
    return ngx_handle.new(
        Lor.nginx_conf_content(),
        scaffold_conf.app_dirs.tmp .. "/" .. scaffold_conf.env .. "-nginx.conf"
    )
end

function Lor.start(env)
    if env == nil then env = scaffold_conf.env end

    local ok, handler = pcall(function() return new_handler() end)
    if ok == false then
        print("ERROR:Cannot initialize handler: " .. handler)
        return
    end

    result = handler:start(env)
    if result == 0 then
        if scaffold_conf.env ~= 'test' then
            print("app in " .. scaffold_conf.env .. " was succesfully started on port " .. ngx_config.PORT)
        end
    else
        print("ERROR: Could not start app on port " .. ngx_config.PORT)
    end
end


function Lor.stop(env)
    if env == nil then env = scaffold_conf.env end

    local handler = new_handler()
    result = handler:stop(env)

    if scaffold_conf.env ~= 'test' then
        if result == 0 then
            print("app in " .. scaffold_conf.env .. " was succesfully stopped.")
        else
            print("ERROR: Could not stop app (are you sure it is running?).")
        end
    end
end


return Lor